### ISSUE TITLE
Note needed in the Readme

### ISSUE THREAD

**Issue by parkerlreed** [cow-killer/dualsense-led-configurator#2]
The LEDs exposure was removed in the latest patches. This program no longer works until that gets added back.

https://patchwork.kernel.org/project/linux-input/cover/20210217173158.3122868-1-benjamin.tissoires@redhat.com/#23985195

**Comment by cow-killer** [comment]
Thanks for letting me know, I guess we'll just have to hang tight for now as I don't think there's anything I can do on my end.

**Comment by cow-killer** [comment]
@parkerlreed You can try this PR out for now; you may need to tinker around a little bit with the script though in order to get it to work. https://github.com/cow-killer/dualsense-led-configurator/pull/3

**Comment by cow-killer** [comment]
This PR has been merged. Going to close this for now. Try running the app again, it should work. If not create another issue.
